### ISSUE TITLE
请问作者实现的是这篇文章相关的代码嘛《Self-Supervised Convolutional Neural Network via Spectral Attention Module for Hyperspectral Image Classification》

### ISSUE THREAD

**Issue by irving2000** [lucanren/sa-scnn-testing#1]

**Comment by chihuajiao** [comment]
Hello, are you also studying this article? Can we communicate with friends together? My email is yhxie2022@163.com.

**Comment by irving2000** [comment]
Good，My WeChat 15261113909




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lucanren/sa-scnn-testing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月18日(星期四) 晚上10:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lucanren/sa-scnn-testing] 请问作者实现的是这篇文章相关的代码嘛《Self-Supervised Convolutional Neural Network via Spectral Attention Module for Hyperspectral Image Classification》 (Issue #1)





 
Hello, are you also studying this article? Can we communicate with friends together? My email is ***@***.***

**Comment by lucanren** [comment]
sorry the sa here is not spectral attention, rather self attention
